### ISSUE TITLE
Trailing newline in persons name.

### ISSUE THREAD

**Issue by msal** [MicMun/MiWoTreff#11]
The JSON feed delivers the persons names with a trailing newline:
http://www.mittwochstreff-muenchen.de/program/api/index.php?op=0&von=0

e.g.

```json
{
    "p_date": "21.01.2015",
    "p_person": "Siggi\n",
    "p_topic": "Gesetze des Alten Testaments"
},
```

Resulting in issues with the list row layout:
![device-2015-03-30-133014](https://cloud.githubusercontent.com/assets/423373/6895565/eafd9fce-d6e1-11e4-9f92-7a7e3d8a801d.png)

**Comment by MicMun** [comment]
Bugfix is merged.

**Comment by MicMun** [comment]
Bugfix is merged.
