### ISSUE TITLE
CustomToast verdeckt SwipeRefreshLayout

### ISSUE THREAD

**Issue by msal** [MicMun/MiWoTreff#14]
`CustomToast` verdeckt `SwipeRefreshLayout`. Eventuell den Toast stattdessen am unteren Bildschirmrand anzeigen?

**Comment by MicMun** [comment]
Der CustomToast erscheint doch erst, wenn es fertig ist.
Braucht man dann noch was vom SwipeRefreshLayout sehen? 
Die ProgressBar müsste da sowieso verschwunden sein.

**Comment by msal** [comment]
Der Progress-Indikator fadet eine gewisse Zeit aus. Vermutlich ca. 200ms.

1. Solange er dreht wird geladen.
2. Laden ist fertig -> der `OnProgramRefreshedListener` feuert
  * es wird zeitgleich `mSwipeLayout.setRefreshing(false)` und `CustomToast.makeText(context, msg, CustomToast.TYPE_INFO).show()` ausgeführt.
3. das führt dazu dass zeitlich der Indicator ausgeblendet wird und der Toast eingeblendet wird, was zu einer Überschneidung der Animationen/Elemente führt.

Eventuell könnte man den Toast auch verzögert (z. B. 300ms, wenn der Indicator 200ms ausblendet) starten.

**Comment by MicMun** [comment]
Ok, das wusste ich nicht.
Und habe ich wegen dem CustomToast auch nicht gesehen ;)

Ich schaue es mir mal an.

**Comment by MicMun** [comment]
Also ich sehe da ohne den CustomToast auch keinen großen Effekt, der vorher verdeckt war.
Der Kreis dreht sich und dann ist er weg.
Mir gefällt die Position nämlich schon, weil der User sowieso dahin schaut, wenn der Kreis da sich bewegt.
Und ich habe lange gebraucht, um die Position so hinzubekommen. Deswegen nutze ich ja die Library AppMsg nicht mehr.
