### ISSUE TITLE
Refresh-Icon in der Toolbar verstecken

### ISSUE THREAD

**Issue by msal** [MicMun/MiWoTreff#16]
Refresh-Icon in der Actionbar würde ich als `showAsAction="never"` machen. Denn es ist viel einfacher die Liste herunterzuziehen, weswegen der Klick auf den Button nur eine sekundäre Alternative darstellt.

**Comment by MicMun** [comment]
Da es mindestens eine Person in unserem Kreis gibt, die bisher bei anderen Apps nur die Icon-Variante kennt und nutzt, verstecke ich das Refresh-Icon besser nicht.
Außerdem gefällt mir optisch die Variante ganz gut.
